### ISSUE TITLE
[Feature request] Any plan for Plasma 6?

### ISSUE THREAD

**Issue by oberkut** [ruinivist/NowPlaying#9]
Hello,

Kde Plamsa 6 will be landed most major distro soon and I've already upgraded to Plasma 6.
Do you have any plan NowPlaying support for Plasma 6? or any workarounds?

Thank you

Best regards,

**Comment by nihilist-dev** [comment]
Too late but yes, I'm back on my kde setup now after using mac for a while. This extension I used in my setup as well so I would fix it, probably by next weekend.

**Comment by nihilist-dev** [comment]
Sorry, too late but yes, I'm back on my kde setup now and I used this in my setup personally, so I'll fix this. Probably by next week

**Comment by ruinivist** [comment]
Sorry, too late but yes, I'm back on my kde setup now and I used this in my setup personally, so I'll fix this. Probably by next week

**Comment by ruinivist** [comment]
hey hey hey, here you go https://www.pling.com/p/2195583/

**Comment by ruinivist** [comment]
lmk if any issues, this was hasty work at best

**Comment by oberkut** [comment]
![Снимок экрана_20240827_115703](https://github.com/user-attachments/assets/07892874-24bd-46d8-8ce1-12f272507c91)
openSUSE Tumbleweed kde 6. Not work.
